# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-10 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='recent_content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=2000, null=True)),
                ('Show_type', models.CharField(blank=True, max_length=100, null=True)),
                ('Source', models.CharField(blank=True, max_length=100, null=True)),
                ('Service', models.CharField(blank=True, max_length=100, null=True)),
                ('content_type', models.CharField(blank=True, max_length=100, null=True)),
                ('Added_to_site', models.CharField(blank=True, max_length=200, null=True)),
                ('Updated_at_DB', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
