# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-11 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='recent_content',
            fields=[
                ('title', models.CharField(max_length=254, primary_key=True, serialize=False)),
                ('Show_type', models.CharField(blank=True, max_length=100, null=True)),
                ('Source', models.CharField(blank=True, max_length=100, null=True)),
                ('Service', models.CharField(blank=True, max_length=100, null=True)),
                ('content_type', models.CharField(blank=True, max_length=100, null=True)),
                ('Added_to_site', models.CharField(blank=True, max_length=200, null=True)),
                ('Updated_at_DB', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
